const fishingFacts = [
'Some fish can recognize familiar sounds and may return to feeding areas when they hear them.',
'Fish do not blink because most of them do not have eyelids.',
'A fish’s scales can show growth rings, similar to tree rings.',
'Many fish are more active during sunrise and sunset.',
'Catfish have taste buds across much of their bodies.',
'Some fish can see ultraviolet light.',
'Quiet anglers often have better fishing success.',
'Fish use their lateral line to detect movement and pressure changes.',
'Water temperature strongly affects fish behavior.',
'Many freshwater fish stay in shaded areas during hot days.',
'Fish gather near underwater plants because they provide shelter.',
'After light rain, fish activity often increases.',
'Wind can push food toward one side of a lake.',
'Larger fish usually stay deeper during the day.',
'Fish can remember places where they found food.',
'Air pressure changes before storms may affect fish activity.',
'Clear water requires a more careful approach.',
'Murky water makes fish rely more on smell and vibration.',
'Rocks, docks and reeds attract many fish.',
'Underwater depth is often more important than the surface view.',
'Some fish can produce sounds.',
'Fish use their swim bladder to control buoyancy.',
'Cold water usually slows fish movement.',
'Very warm water reduces oxygen levels.',
'Many anglers believe moon phases influence feeding.',
'Shadows can scare fish in shallow water.',
'Small ripples help hide movement.',
'Early morning fog often means calm water.',
'Birds diving over water may reveal fish activity.',
'The best fishing places are often hidden from the main paths.'
];

export default fishingFacts;